import type { Metadata } from "next";
import "./globals.css";
import NavbarLayout from "@/components/Navbar/NavbarLayout";
import FooterPage from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavbarLayout/>
        {children}
        <FooterPage/>
      </body>
    </html>
  );
}
